language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: qu+szyj1wCkRRtw74CcfiTAIbSRLZQXlUnvemfCvgwZ7ZRrDqZljahWzVas1CCLHBBxCb/QUsD7Lggi1y0hhRIMPSHal8YEPR0KOoe3EgrupakUtpAo0yvPjsP/Qy7BhUPZ7s8yk9eEWL1MznTbDlTlVeazVauiFbrgUAYakW5aOVa5TuR/1dG/rl26EsiH41uPri86lVLI1JJiDmmEEJkMdIG47f5+hWgCJvFYSl82cX6GMwqoAOrn6ZMQiKuXi/B01PLvxRasYpymeiDcxywLL2Hg2N1BM3woTTrikgb8GknmimbMKo8JO4bHXLFbQRqEf/G5JITFc4nOMCzHav+kfmVy6V0pgU3RfMPwU5xDssyRXhKiTrPEfmu7pVrDGU6+ASnLgx+UMeK0yRV0Ls8ykKH0oEM7wXoSNE00eb5Si8eNoDAp/MraUUUEjKcOwSDkwRQy9rO1pda1Y1ZI+wxrD1J/cLC55NXluT3RAP4cwvkIhbFioi1qjUlSP36QR4v4eBy+BBuvNrDjKq9DFDg8C8b0CF82ZpkaLzdWfkPc2yk1TYSmXwZUpIzaNS3rCWF1kIS6+yOP2XKhWBCrTot/Akheqr1xIM8BsqXBV+2fqNxzV+bHsFCsdQMShUmyS5u2vTBdXwwrZAiQ2MLAWn9PQT+OMFUlwIgb3aBVWlhc=
